name: paperMC-learning
version: '1.0.0'
main: m1jawa.paperMCLearning.PaperMCLearning
api-version: '1.21'
commands:
  roll:
    default-permission: notop
  color-msg:
    default-permission: notop
  get-item:
    default-permission: notop